import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_core/firebase_core.dart';
import '../firebase_options.dart';

Future<void> importarApartamentosB() async {
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  final firestore = FirebaseFirestore.instance;
  final batch = firestore.batch();

  batch.set(firestore.collection('apartamentos').doc('apt_001_b_hera'), {'numero': 1, 'tipo': 'Luxo Master', 'andar': 'Térreo', 'checkin': 'sexta', 'bloco': 'B (Hera)'});
  batch.set(firestore.collection('apartamentos').doc('apt_002_b_hera'), {'numero': 2, 'tipo': 'Luxo', 'andar': 'Térreo', 'checkin': 'sábado', 'bloco': 'B (Hera)'});
  batch.set(firestore.collection('apartamentos').doc('apt_003_b_hera'), {'numero': 3, 'tipo': 'Luxo', 'andar': 'Térreo', 'checkin': 'domingo', 'bloco': 'B (Hera)'});
  batch.set(firestore.collection('apartamentos').doc('apt_004_b_hera'), {'numero': 4, 'tipo': 'Luxo', 'andar': 'Térreo', 'checkin': 'segunda', 'bloco': 'B (Hera)'});
  batch.set(firestore.collection('apartamentos').doc('apt_005_b_hera'), {'numero': 5, 'tipo': 'Luxo', 'andar': 'Térreo', 'checkin': 'quinta', 'bloco': 'B (Hera)'});
  batch.set(firestore.collection('apartamentos').doc('apt_007_b_hera'), {'numero': 7, 'tipo': 'Luxo', 'andar': 'Térreo', 'checkin': 'sexta', 'bloco': 'B (Hera)'});
  batch.set(firestore.collection('apartamentos').doc('apt_008_b_hera'), {'numero': 8, 'tipo': 'Luxo', 'andar': 'Térreo', 'checkin': 'sábado', 'bloco': 'B (Hera)'});
  batch.set(firestore.collection('apartamentos').doc('apt_009_b_hera'), {'numero': 9, 'tipo': 'Luxo', 'andar': 'Térreo', 'checkin': 'domingo', 'bloco': 'B (Hera)'});
  batch.set(firestore.collection('apartamentos').doc('apt_010_b_hera'), {'numero': 10, 'tipo': 'Luxo', 'andar': 'Térreo', 'checkin': 'segunda', 'bloco': 'B (Hera)'});
  batch.set(firestore.collection('apartamentos').doc('apt_011_b_hera'), {'numero': 11, 'tipo': 'Luxo', 'andar': 'Térreo', 'checkin': 'quinta', 'bloco': 'B (Hera)'});
  batch.set(firestore.collection('apartamentos').doc('apt_012_b_hera'), {'numero': 12, 'tipo': 'Luxo', 'andar': 'Térreo', 'checkin': 'sexta', 'bloco': 'B (Hera)'});
  batch.set(firestore.collection('apartamentos').doc('apt_013_b_hera'), {'numero': 13, 'tipo': 'Luxo', 'andar': 'Térreo', 'checkin': 'sábado', 'bloco': 'B (Hera)'});
  batch.set(firestore.collection('apartamentos').doc('apt_014_b_hera'), {'numero': 14, 'tipo': 'Luxo', 'andar': 'Térreo', 'checkin': 'domingo', 'bloco': 'B (Hera)'});
  batch.set(firestore.collection('apartamentos').doc('apt_016_b_hera'), {'numero': 16, 'tipo': 'Luxo', 'andar': 'Térreo', 'checkin': 'segunda', 'bloco': 'B (Hera)'});
  batch.set(firestore.collection('apartamentos').doc('apt_017_b_hera'), {'numero': 17, 'tipo': 'Luxo', 'andar': 'Térreo', 'checkin': 'quinta', 'bloco': 'B (Hera)'});
  batch.set(firestore.collection('apartamentos').doc('apt_018_b_hera'), {'numero': 18, 'tipo': 'Luxo', 'andar': 'Térreo', 'checkin': 'sexta', 'bloco': 'B (Hera)'});
  batch.set(firestore.collection('apartamentos').doc('apt_019_b_hera'), {'numero': 19, 'tipo': 'Luxo', 'andar': 'Térreo', 'checkin': 'sábado', 'bloco': 'B (Hera)'});
  batch.set(firestore.collection('apartamentos').doc('apt_020_b_hera'), {'numero': 20, 'tipo': 'Luxo Premium', 'andar': 'Térreo', 'checkin': 'domingo', 'bloco': 'B (Hera)'});
  batch.set(firestore.collection('apartamentos').doc('apt_101_b_hera'), {'numero': 101, 'tipo': 'Luxo Master', 'andar': '1º Pavimento', 'checkin': 'segunda', 'bloco': 'B (Hera)'});
  batch.set(firestore.collection('apartamentos').doc('apt_102_b_hera'), {'numero': 102, 'tipo': 'Luxo', 'andar': '1º Pavimento', 'checkin': 'quinta', 'bloco': 'B (Hera)'});
  batch.set(firestore.collection('apartamentos').doc('apt_103_b_hera'), {'numero': 103, 'tipo': 'Luxo', 'andar': '1º Pavimento', 'checkin': 'sexta', 'bloco': 'B (Hera)'});
  batch.set(firestore.collection('apartamentos').doc('apt_104_b_hera'), {'numero': 104, 'tipo': 'Luxo', 'andar': '1º Pavimento', 'checkin': 'sábado', 'bloco': 'B (Hera)'});
  batch.set(firestore.collection('apartamentos').doc('apt_105_b_hera'), {'numero': 105, 'tipo': 'Luxo', 'andar': '1º Pavimento', 'checkin': 'domingo', 'bloco': 'B (Hera)'});
  batch.set(firestore.collection('apartamentos').doc('apt_106_b_hera'), {'numero': 106, 'tipo': 'Luxo', 'andar': '1º Pavimento', 'checkin': 'segunda', 'bloco': 'B (Hera)'});
  batch.set(firestore.collection('apartamentos').doc('apt_107_b_hera'), {'numero': 107, 'tipo': 'Luxo', 'andar': '1º Pavimento', 'checkin': 'quinta', 'bloco': 'B (Hera)'});
  batch.set(firestore.collection('apartamentos').doc('apt_108_b_hera'), {'numero': 108, 'tipo': 'Luxo', 'andar': '1º Pavimento', 'checkin': 'sexta', 'bloco': 'B (Hera)'});
  batch.set(firestore.collection('apartamentos').doc('apt_109_b_hera'), {'numero': 109, 'tipo': 'Luxo', 'andar': '1º Pavimento', 'checkin': 'sábado', 'bloco': 'B (Hera)'});
  batch.set(firestore.collection('apartamentos').doc('apt_110_b_hera'), {'numero': 110, 'tipo': 'Luxo', 'andar': '1º Pavimento', 'checkin': 'domingo', 'bloco': 'B (Hera)'});
  batch.set(firestore.collection('apartamentos').doc('apt_111_b_hera'), {'numero': 111, 'tipo': 'Luxo', 'andar': '1º Pavimento', 'checkin': 'segunda', 'bloco': 'B (Hera)'});
  batch.set(firestore.collection('apartamentos').doc('apt_112_b_hera'), {'numero': 112, 'tipo': 'Luxo', 'andar': '1º Pavimento', 'checkin': 'quinta', 'bloco': 'B (Hera)'});
  batch.set(firestore.collection('apartamentos').doc('apt_113_b_hera'), {'numero': 113, 'tipo': 'Luxo', 'andar': '1º Pavimento', 'checkin': 'sexta', 'bloco': 'B (Hera)'});
  batch.set(firestore.collection('apartamentos').doc('apt_114_b_hera'), {'numero': 114, 'tipo': 'Luxo', 'andar': '1º Pavimento', 'checkin': 'sábado', 'bloco': 'B (Hera)'});
  batch.set(firestore.collection('apartamentos').doc('apt_115_b_hera'), {'numero': 115, 'tipo': 'Luxo', 'andar': '1º Pavimento', 'checkin': 'domingo', 'bloco': 'B (Hera)'});
  batch.set(firestore.collection('apartamentos').doc('apt_116_b_hera'), {'numero': 116, 'tipo': 'Luxo', 'andar': '1º Pavimento', 'checkin': 'segunda', 'bloco': 'B (Hera)'});
  batch.set(firestore.collection('apartamentos').doc('apt_117_b_hera'), {'numero': 117, 'tipo': 'Luxo', 'andar': '1º Pavimento', 'checkin': 'quinta', 'bloco': 'B (Hera)'});
  batch.set(firestore.collection('apartamentos').doc('apt_118_b_hera'), {'numero': 118, 'tipo': 'Luxo', 'andar': '1º Pavimento', 'checkin': 'sexta', 'bloco': 'B (Hera)'});
  batch.set(firestore.collection('apartamentos').doc('apt_119_b_hera'), {'numero': 119, 'tipo': 'Luxo', 'andar': '1º Pavimento', 'checkin': 'sábado', 'bloco': 'B (Hera)'});
  batch.set(firestore.collection('apartamentos').doc('apt_120_b_hera'), {'numero': 120, 'tipo': 'Luxo Premium', 'andar': '1º Pavimento', 'checkin': 'domingo', 'bloco': 'B (Hera)'});
  batch.set(firestore.collection('apartamentos').doc('apt_201_b_hera'), {'numero': 201, 'tipo': 'Luxo Master', 'andar': '2º Pavimento', 'checkin': 'segunda', 'bloco': 'B (Hera)'});
  batch.set(firestore.collection('apartamentos').doc('apt_202_b_hera'), {'numero': 202, 'tipo': 'Luxo', 'andar': '2º Pavimento', 'checkin': 'quinta', 'bloco': 'B (Hera)'});
  batch.set(firestore.collection('apartamentos').doc('apt_203_b_hera'), {'numero': 203, 'tipo': 'Luxo', 'andar': '2º Pavimento', 'checkin': 'sexta', 'bloco': 'B (Hera)'});
  batch.set(firestore.collection('apartamentos').doc('apt_204_b_hera'), {'numero': 204, 'tipo': 'Luxo', 'andar': '2º Pavimento', 'checkin': 'sábado', 'bloco': 'B (Hera)'});
  batch.set(firestore.collection('apartamentos').doc('apt_205_b_hera'), {'numero': 205, 'tipo': 'Luxo', 'andar': '2º Pavimento', 'checkin': 'domingo', 'bloco': 'B (Hera)'});
  batch.set(firestore.collection('apartamentos').doc('apt_206_b_hera'), {'numero': 206, 'tipo': 'Luxo', 'andar': '2º Pavimento', 'checkin': 'segunda', 'bloco': 'B (Hera)'});
  batch.set(firestore.collection('apartamentos').doc('apt_207_b_hera'), {'numero': 207, 'tipo': 'Luxo', 'andar': '2º Pavimento', 'checkin': 'quinta', 'bloco': 'B (Hera)'});
  batch.set(firestore.collection('apartamentos').doc('apt_208_b_hera'), {'numero': 208, 'tipo': 'Luxo', 'andar': '2º Pavimento', 'checkin': 'sexta', 'bloco': 'B (Hera)'});
  batch.set(firestore.collection('apartamentos').doc('apt_209_b_hera'), {'numero': 209, 'tipo': 'Luxo', 'andar': '2º Pavimento', 'checkin': 'sábado', 'bloco': 'B (Hera)'});
  batch.set(firestore.collection('apartamentos').doc('apt_210_b_hera'), {'numero': 210, 'tipo': 'Luxo', 'andar': '2º Pavimento', 'checkin': 'domingo', 'bloco': 'B (Hera)'});
  batch.set(firestore.collection('apartamentos').doc('apt_211_b_hera'), {'numero': 211, 'tipo': 'Luxo', 'andar': '2º Pavimento', 'checkin': 'segunda', 'bloco': 'B (Hera)'});
  batch.set(firestore.collection('apartamentos').doc('apt_212_b_hera'), {'numero': 212, 'tipo': 'Luxo', 'andar': '2º Pavimento', 'checkin': 'quinta', 'bloco': 'B (Hera)'});
  batch.set(firestore.collection('apartamentos').doc('apt_213_b_hera'), {'numero': 213, 'tipo': 'Luxo', 'andar': '2º Pavimento', 'checkin': 'sexta', 'bloco': 'B (Hera)'});
  batch.set(firestore.collection('apartamentos').doc('apt_214_b_hera'), {'numero': 214, 'tipo': 'Luxo', 'andar': '2º Pavimento', 'checkin': 'sábado', 'bloco': 'B (Hera)'});
  batch.set(firestore.collection('apartamentos').doc('apt_215_b_hera'), {'numero': 215, 'tipo': 'Luxo', 'andar': '2º Pavimento', 'checkin': 'domingo', 'bloco': 'B (Hera)'});
  batch.set(firestore.collection('apartamentos').doc('apt_216_b_hera'), {'numero': 216, 'tipo': 'Luxo', 'andar': '2º Pavimento', 'checkin': 'segunda', 'bloco': 'B (Hera)'});
  batch.set(firestore.collection('apartamentos').doc('apt_217_b_hera'), {'numero': 217, 'tipo': 'Luxo', 'andar': '2º Pavimento', 'checkin': 'quinta', 'bloco': 'B (Hera)'});
  batch.set(firestore.collection('apartamentos').doc('apt_218_b_hera'), {'numero': 218, 'tipo': 'Luxo', 'andar': '2º Pavimento', 'checkin': 'sexta', 'bloco': 'B (Hera)'});
  batch.set(firestore.collection('apartamentos').doc('apt_219_b_hera'), {'numero': 219, 'tipo': 'Luxo', 'andar': '2º Pavimento', 'checkin': 'sábado', 'bloco': 'B (Hera)'});
  batch.set(firestore.collection('apartamentos').doc('apt_220_b_hera'), {'numero': 220, 'tipo': 'Luxo Premium', 'andar': '2º Pavimento', 'checkin': 'domingo', 'bloco': 'B (Hera)'});
  batch.set(firestore.collection('apartamentos').doc('apt_301_b_hera'), {'numero': 301, 'tipo': 'Luxo Master', 'andar': '3º Pavimento', 'checkin': 'segunda', 'bloco': 'B (Hera)'});
  batch.set(firestore.collection('apartamentos').doc('apt_302_b_hera'), {'numero': 302, 'tipo': 'Luxo', 'andar': '3º Pavimento', 'checkin': 'quinta', 'bloco': 'B (Hera)'});
  batch.set(firestore.collection('apartamentos').doc('apt_303_b_hera'), {'numero': 303, 'tipo': 'Luxo', 'andar': '3º Pavimento', 'checkin': 'sexta', 'bloco': 'B (Hera)'});
  batch.set(firestore.collection('apartamentos').doc('apt_304_b_hera'), {'numero': 304, 'tipo': 'Luxo', 'andar': '3º Pavimento', 'checkin': 'sábado', 'bloco': 'B (Hera)'});
  batch.set(firestore.collection('apartamentos').doc('apt_305_b_hera'), {'numero': 305, 'tipo': 'Luxo', 'andar': '3º Pavimento', 'checkin': 'domingo', 'bloco': 'B (Hera)'});
  batch.set(firestore.collection('apartamentos').doc('apt_306_b_hera'), {'numero': 306, 'tipo': 'Luxo', 'andar': '3º Pavimento', 'checkin': 'segunda', 'bloco': 'B (Hera)'});
  batch.set(firestore.collection('apartamentos').doc('apt_307_b_hera'), {'numero': 307, 'tipo': 'Luxo', 'andar': '3º Pavimento', 'checkin': 'quinta', 'bloco': 'B (Hera)'});
  batch.set(firestore.collection('apartamentos').doc('apt_308_b_hera'), {'numero': 308, 'tipo': 'Luxo', 'andar': '3º Pavimento', 'checkin': 'sexta', 'bloco': 'B (Hera)'});
  batch.set(firestore.collection('apartamentos').doc('apt_309_b_hera'), {'numero': 309, 'tipo': 'Luxo', 'andar': '3º Pavimento', 'checkin': 'sábado', 'bloco': 'B (Hera)'});
  batch.set(firestore.collection('apartamentos').doc('apt_310_b_hera'), {'numero': 310, 'tipo': 'Luxo', 'andar': '3º Pavimento', 'checkin': 'domingo', 'bloco': 'B (Hera)'});
  batch.set(firestore.collection('apartamentos').doc('apt_311_b_hera'), {'numero': 311, 'tipo': 'Luxo', 'andar': '3º Pavimento', 'checkin': 'segunda', 'bloco': 'B (Hera)'});
  batch.set(firestore.collection('apartamentos').doc('apt_312_b_hera'), {'numero': 312, 'tipo': 'Luxo', 'andar': '3º Pavimento', 'checkin': 'quinta', 'bloco': 'B (Hera)'});
  batch.set(firestore.collection('apartamentos').doc('apt_313_b_hera'), {'numero': 313, 'tipo': 'Luxo', 'andar': '3º Pavimento', 'checkin': 'sexta', 'bloco': 'B (Hera)'});
  batch.set(firestore.collection('apartamentos').doc('apt_314_b_hera'), {'numero': 314, 'tipo': 'Luxo', 'andar': '3º Pavimento', 'checkin': 'sábado', 'bloco': 'B (Hera)'});
  batch.set(firestore.collection('apartamentos').doc('apt_315_b_hera'), {'numero': 315, 'tipo': 'Luxo', 'andar': '3º Pavimento', 'checkin': 'domingo', 'bloco': 'B (Hera)'});
  batch.set(firestore.collection('apartamentos').doc('apt_316_b_hera'), {'numero': 316, 'tipo': 'Luxo', 'andar': '3º Pavimento', 'checkin': 'segunda', 'bloco': 'B (Hera)'});
  batch.set(firestore.collection('apartamentos').doc('apt_317_b_hera'), {'numero': 317, 'tipo': 'Luxo', 'andar': '3º Pavimento', 'checkin': 'quinta', 'bloco': 'B (Hera)'});
  batch.set(firestore.collection('apartamentos').doc('apt_318_b_hera'), {'numero': 318, 'tipo': 'Luxo', 'andar': '3º Pavimento', 'checkin': 'sexta', 'bloco': 'B (Hera)'});
  batch.set(firestore.collection('apartamentos').doc('apt_319_b_hera'), {'numero': 319, 'tipo': 'Luxo', 'andar': '3º Pavimento', 'checkin': 'sábado', 'bloco': 'B (Hera)'});
  batch.set(firestore.collection('apartamentos').doc('apt_320_b_hera'), {'numero': 320, 'tipo': 'Luxo Premium', 'andar': '3º Pavimento', 'checkin': 'domingo', 'bloco': 'B (Hera)'});
  batch.set(firestore.collection('apartamentos').doc('apt_402_b_hera'), {'numero': 402, 'tipo': 'Luxo', 'andar': '4º Pavimento', 'checkin': 'sexta', 'bloco': 'B (Hera)'});
  batch.set(firestore.collection('apartamentos').doc('apt_403_b_hera'), {'numero': 403, 'tipo': 'Luxo', 'andar': '4º Pavimento', 'checkin': 'sábado', 'bloco': 'B (Hera)'});
  batch.set(firestore.collection('apartamentos').doc('apt_404_b_hera'), {'numero': 404, 'tipo': 'Luxo', 'andar': '4º Pavimento', 'checkin': 'domingo', 'bloco': 'B (Hera)'});
  batch.set(firestore.collection('apartamentos').doc('apt_405_b_hera'), {'numero': 405, 'tipo': 'Luxo', 'andar': '4º Pavimento', 'checkin': 'segunda', 'bloco': 'B (Hera)'});
  batch.set(firestore.collection('apartamentos').doc('apt_406_b_hera'), {'numero': 406, 'tipo': 'Luxo', 'andar': '4º Pavimento', 'checkin': 'quinta', 'bloco': 'B (Hera)'});
  batch.set(firestore.collection('apartamentos').doc('apt_407_b_hera'), {'numero': 407, 'tipo': 'Luxo', 'andar': '4º Pavimento', 'checkin': 'sexta', 'bloco': 'B (Hera)'});
  batch.set(firestore.collection('apartamentos').doc('apt_408_b_hera'), {'numero': 408, 'tipo': 'Luxo', 'andar': '4º Pavimento', 'checkin': 'sábado', 'bloco': 'B (Hera)'});
  batch.set(firestore.collection('apartamentos').doc('apt_409_b_hera'), {'numero': 409, 'tipo': 'Luxo', 'andar': '4º Pavimento', 'checkin': 'domingo', 'bloco': 'B (Hera)'});
  batch.set(firestore.collection('apartamentos').doc('apt_410_b_hera'), {'numero': 410, 'tipo': 'Luxo', 'andar': '4º Pavimento', 'checkin': 'segunda', 'bloco': 'B (Hera)'});
  batch.set(firestore.collection('apartamentos').doc('apt_411_b_hera'), {'numero': 411, 'tipo': 'Luxo', 'andar': '4º Pavimento', 'checkin': 'quinta', 'bloco': 'B (Hera)'});
  batch.set(firestore.collection('apartamentos').doc('apt_412_b_hera'), {'numero': 412, 'tipo': 'Luxo', 'andar': '4º Pavimento', 'checkin': 'sexta', 'bloco': 'B (Hera)'});
  batch.set(firestore.collection('apartamentos').doc('apt_413_b_hera'), {'numero': 413, 'tipo': 'Luxo', 'andar': '4º Pavimento', 'checkin': 'sábado', 'bloco': 'B (Hera)'});
  batch.set(firestore.collection('apartamentos').doc('apt_414_b_hera'), {'numero': 414, 'tipo': 'Luxo', 'andar': '4º Pavimento', 'checkin': 'domingo', 'bloco': 'B (Hera)'});
  batch.set(firestore.collection('apartamentos').doc('apt_415_b_hera'), {'numero': 415, 'tipo': 'Luxo', 'andar': '4º Pavimento', 'checkin': 'segunda', 'bloco': 'B (Hera)'});
  batch.set(firestore.collection('apartamentos').doc('apt_416_b_hera'), {'numero': 416, 'tipo': 'Luxo', 'andar': '4º Pavimento', 'checkin': 'quinta', 'bloco': 'B (Hera)'});
  batch.set(firestore.collection('apartamentos').doc('apt_417_b_hera'), {'numero': 417, 'tipo': 'Luxo', 'andar': '4º Pavimento', 'checkin': 'sexta', 'bloco': 'B (Hera)'});
  batch.set(firestore.collection('apartamentos').doc('apt_418_b_hera'), {'numero': 418, 'tipo': 'Luxo', 'andar': '4º Pavimento', 'checkin': 'sábado', 'bloco': 'B (Hera)'});
  batch.set(firestore.collection('apartamentos').doc('apt_420_b_hera'), {'numero': 420, 'tipo': 'Luxo Premium', 'andar': '4º Pavimento', 'checkin': 'segunda', 'bloco': 'B (Hera)'});
  batch.set(firestore.collection('apartamentos').doc('apt_50001_b_hera'), {'numero': 50001, 'tipo': 'Luxo Master', 'andar': '4º Pavimento', 'checkin': 'quinta', 'bloco': 'B (Hera)'});
  batch.set(firestore.collection('apartamentos').doc('apt_519_b_hera'), {'numero': 519, 'tipo': 'Luxo', 'andar': '4º Pavimento', 'checkin': 'domingo', 'bloco': 'B (Hera)'});

  await batch.commit();
  print('✅ Importação de apartamentos concluída.');
}